"""Constraint 2

Revision ID: cbd2fc2ee8b1
Revises: 09aa4ddeff21
Create Date: 2026-03-12 18:26:25.841090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbd2fc2ee8b1'
down_revision: Union[str, Sequence[str], None] = '09aa4ddeff21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
